# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32)),
            ],
        ),
    ]
